name: main

on:
  push:
    branches: [$default-branch]
  pull_request: {}

jobs:
  main:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ubuntu-latest
    env:
      POETRY_VIRTUALENVS_IN_PROJECT: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: pip install poetry==1.6.1
      - name: cache venv
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - run: poetry install
      - name: static analysis
        run: |
          poetry run black --check src tests
          poetry run mypy src tests
      - name: run tests
        run: |
          poetry run pytest
          poetry run autotrash --help
